import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar/navbar";
import { headingFontItalic, headingFontRegular, primaryFont } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${primaryFont.variable}${headingFontItalic.variable}${headingFontRegular.variable}`}>
      <body
        className={`${primaryFont.className} mx-6 md:mx-24`}
        >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
